"""Distributor: MP3 -> Cloudflare R2 upload + Discourse episode post.

Uploads the rendered episode to R2 (S3-compatible), then posts show notes
with an embedded audio player back to the forum. Requires [distribute] extra:
    uv sync --extra distribute

If R2 credentials are empty, skips upload and prints show notes locally
(useful for testing curator + renderer before cloud setup).

Standalone:
    uv run python -m src.distributor output/YYYY-MM-DD-episode.mp3 [script.json]
"""

from __future__ import annotations

import json
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import httpx

from src.config import RadioConfig, load_config

# ---------------------------------------------------------------------------
# R2 upload
# ---------------------------------------------------------------------------


def _upload_to_r2(
    config: RadioConfig,
    file_path: Path,
    key: str,
    content_type: str = "audio/mpeg",
) -> str:
    """Upload a file to Cloudflare R2. Returns public URL."""
    try:
        import boto3
        from botocore.config import Config
    except ImportError as exc:
        raise ImportError(
            "boto3 is required for R2 uploads.\nInstall with: uv sync --extra distribute"
        ) from exc

    s3 = boto3.client(
        "s3",
        endpoint_url=config.distributor.r2_endpoint,
        aws_access_key_id=config.distributor.r2_access_key_id,
        aws_secret_access_key=config.distributor.r2_secret_access_key,
        config=Config(signature_version="s3v4"),
        region_name="auto",
    )

    with file_path.open("rb") as f:
        s3.put_object(
            Bucket=config.distributor.r2_bucket,
            Key=key,
            Body=f,
            ContentType=content_type,
        )

    return f"{config.distributor.public_url_base.rstrip('/')}/{key}"


# ---------------------------------------------------------------------------
# Show notes builder
# ---------------------------------------------------------------------------


def _build_show_notes(script: dict[str, Any], audio_url: str) -> str:
    """Build Markdown post body for the Discourse episode thread."""
    title = str(script.get("title", "Episode"))
    date = str(script.get("date", ""))
    summary = str(script.get("summary", ""))
    threads: list[dict[str, Any]] = script.get("threads_referenced", [])

    lines = [
        f"## {title}",
        f"*{date}*",
        "",
        summary,
        "",
        (
            f'<audio controls preload="metadata">'
            f'<source src="{audio_url}" type="audio/mpeg">'
            f"Your browser does not support audio playback."
            f"</audio>"
        ),
        "",
        "### Threads discussed",
        "",
    ]

    for thread in threads:
        lines.append(f"- [{thread['title']}]({thread['url']})")

    lines += [
        "",
        "---",
        "*Generated by [Agent Radio](https://github.com/ainorthwest/agent-radio) — "
        "the AINW daily digest.*",
    ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Discourse post
# ---------------------------------------------------------------------------


def _post_to_discourse(config: RadioConfig, title: str, body: str) -> str:
    """Create a new Discourse topic with show notes. Returns post URL."""
    headers = {
        "Api-Key": config.discourse.api_key,
        "Api-Username": config.discourse.api_username,
    }
    payload: dict[str, Any] = {
        "title": title,
        "raw": body,
    }
    if config.distributor.discourse_category:
        try:
            payload["category"] = int(config.distributor.discourse_category)
        except ValueError:
            pass  # skip if not a valid integer — topic will be uncategorized

    with httpx.Client(base_url=config.discourse.base_url, timeout=30) as client:
        resp = client.post("/posts.json", headers=headers, json=payload)
        resp.raise_for_status()
        data: dict[str, Any] = resp.json()

    topic_id = data.get("topic_id", "")
    slug = data.get("topic_slug", "")
    return f"{config.discourse.base_url}/t/{slug}/{topic_id}"


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------


def distribute(
    config: RadioConfig,
    mp3_path: Path,
    script_path: Path,
    r2_key_override: str | None = None,
    library_root: Path | None = None,
) -> str:
    """Upload MP3 to R2 and post show notes to Discourse. Returns post URL (or audio URL)."""
    with script_path.open() as f:
        script: dict[str, Any] = json.load(f)

    date_str = str(script.get("date", datetime.now(UTC).strftime("%Y-%m-%d")))
    r2_key = r2_key_override or f"episodes/{date_str}.mp3"

    # --- Upload ---
    has_r2_creds = bool(config.distributor.r2_bucket and config.distributor.r2_access_key_id)
    if has_r2_creds:
        print(f"Uploading {mp3_path.name} to R2 ({r2_key})...")
        audio_url = _upload_to_r2(config, mp3_path, r2_key)
        print(f"  Uploaded: {audio_url}")
    else:
        print("R2 credentials not configured — skipping upload.")
        audio_url = f"[local] {mp3_path}"

    # --- Upload artwork to R2 (idempotent — same key each time, overwrites) ---
    if has_r2_creds and library_root:
        _manifest_path = mp3_path.parent / "manifest.json"
        if _manifest_path.exists():
            try:
                _manifest = json.loads(_manifest_path.read_text())
                _art_str = _manifest.get("artwork_path")
                if _art_str and Path(_art_str).exists():
                    _art_key = Path(_art_str).relative_to(library_root).as_posix()
                    _upload_to_r2(config, Path(_art_str), _art_key, content_type="image/png")
                    print(f"  Artwork: {config.distributor.public_url_base.rstrip('/')}/{_art_key}")
            except Exception as exc:
                print(f"  WARNING: Artwork upload failed: {exc}")

    # --- Regenerate podcast RSS feed ---
    if has_r2_creds:
        try:
            from src.podcast import generate_feed

            feed_path = generate_feed(
                public_url_base=config.distributor.public_url_base,
                library_root=library_root,
            )
            # Upload feed.xml to R2
            _upload_to_r2(config, feed_path, "feed.xml")
            print(f"  Podcast feed uploaded: {config.distributor.public_url_base}/feed.xml")
        except Exception as exc:
            print(f"  WARNING: Podcast feed generation failed: {exc}")

    # --- Post to Discourse ---
    show_notes = _build_show_notes(script, audio_url)
    post_title = f"Agent Radio — {date_str}: {script.get('title', '')}"

    if config.distributor.post_to_discourse and has_r2_creds:
        print("Posting to Discourse...")
        post_url = _post_to_discourse(config, post_title, show_notes)
        print(f"  Posted: {post_url}")
        return post_url
    else:
        if config.distributor.post_to_discourse and not has_r2_creds:
            print(
                "Discourse post skipped — R2 credentials not configured "
                "(post_to_discourse=True requires r2_bucket + r2_access_key_id)."
            )
        elif not config.distributor.post_to_discourse:
            print("Discourse post skipped — post_to_discourse=False in config.")
        print("\n--- Show notes (not posted) ---")
        print(show_notes)
        return audio_url


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: uv run python -m src.distributor <episode.mp3> [script.json]")
        sys.exit(1)

    cfg = load_config()
    mp3 = Path(sys.argv[1])

    if len(sys.argv) >= 3:
        script = Path(sys.argv[2])
    else:
        # Infer script path from MP3 name: YYYY-MM-DD-episode.mp3 -> YYYY-MM-DD-script.json
        script = mp3.parent / (mp3.stem.replace("-episode", "-script") + ".json")

    distribute(cfg, mp3, script)
